const quotes = [
  "“I spy with my little eye something beginning with a little boy that isn’t working.” - Mr Gilbert",
  "“Pick up ya dummy”- Mrs Hughes",
  "“Nooooo Miss” - Angus Butcher",
  "“What the b#tch” - Angus Butcher",
  "“Just ahhh, Cut the chat there fellas” - Mr Culnane",
  "“What did Romeo and Juliet do? Bow chicka wow wow” - Ms Hardwick",
  "“Guys just ahh, pack up the prac now. Time to ahh get changed.” - Mr Culnane",
  "“Give that kid a peanut.” - Mr Jessett",
  "“He’s earned his m’n’m” *inserts hand into drawer* here you go!” - Mr Jessett",
  "*Ewen and Jacob forget Josh has a nut allergy and put nuts in his pencil case* “Joshua, give me your pencil case and I’ll wash it out for you” - Pughy",
  "“AAAHHHH Year_INSERT YOU YEAR GROUP HERE_” - Miss Heagney",
  "“Where we dropin boys? The bible” - Joshua Borland",
  "“Where we dropping boys” - Liam Cooke",
  "“bOyS hAvE yOu dOnE yoUr crOssWorD?” - Mrs King",
  "“If you’re left handed you’re retarded” - Lochie Hughes",
  "“You're confusing my confusion!” - Mrs Tilley",
  "“Your 50 minutes start when you stop talking!” - Miss Heagney",
  "“Guys, if you can last 10 minutes with ABSOLUTE SILENCE you can listen to music” - Miss Heagney",
  "“Uhhh Gentlemen, put away your iiiiiiiiiiiiiihhhh-paaaaaaadssss” - Mrs King",
  "“Screeeeeeeeeeeeeeeeeeeeeeeeeeeeee (mouth whistle sound)” - Miss Bonnie",
  "*pulls a crossword off a website online* “If this crossword sucks, remember I didn’t make it” - Mrs King",
  "*spends 10 minutes explaining the extra work* “Ahhhh, I’m bored. Let’s play a game!” - Mr Kleinchafer",
  "“Lochie your like my puppy that I lock in the laundry when he’s naughty” “I won’t hesitate”- Mrs King",
  "“Guys ahh, were just gonna watch a errr, a short video to finish off the lesson just cut the chat there boys” - Mr Culnane",
  "“Joyful is spelled goyefull” - Miss Fahy",
  "*Everyone finds random photos of Fahy as a young adult* “Guys, can you just stooooop? Hahahahaha” - Miss Fahy",
  "Liam: *Breathes* “Liam Cooke, give me your record book. You too Harvey, and Ethan, and Lachy.” - Miss Fahy",
  "“Shoan, Seen. How do you say that? Shane Farraway?” - Miss Fahy",
  "“Don’t be the big man, cause you're not.” - Mr Welsh",
  "“Let’s get some MarioKart goin” - Lochie Hughes",
  "“Do you feel intimidated?” - Year 9 to (insert teacher here)",
  "“Pontious.” *wait a few seconds* “Pilate.” - Ben Watson-Tauaalo",
  "“Gotta plan?” - Ben Watson-Tauaalo",
  "“You look like the president from Pixels” “Why? Is it cause I’m fat?” - Josh Borland and Ms Sverdloff",
  "“Please stop, you’re distracting my learning” - Pete",
  "“Jacob, I can picture you as a brain surgeon” “Is it cause I’m Indian?” “Yes”- Miss Sverdloff. ",
  "*like 20 minutes till the bell* “Guys, the bells about to go, let’s get a move on.” - Miss Jones",
  "“To remember Cat-Ion you need to remember positive for puss” - Mr Jessett",
  "“STEAL HIS SHOES”- Ben Watson",
  "“Why is Macauley in the bin?” “Why is Macauley in a stool?” - Mr Pugh",
  "“Guys, quiet down please. GUYS, qUIeT dOwN pleAsE” - Mr Pugh",
  "“O K Boys!” *sees Sean F. pick up a chair and attempt to throw it at Lochie Hughes* “Sean, put the chair down and give me your record book.” - Mr Willis",
  "“Liam, André, give me your record book!” *liam starts screeching* “BUT SIR, ANDRE WAS DISTRACTING ME!” - Liam and Mr Willis",
  "*going around the RE room* “Broken.” *few seconds later* “Charger.” - Lachie Macauley",
  "“Wait..who got the award for most confused?? I mean improved”- Elijah Hoolahan",
  "“Tom, What parable did you do?” “I did the parable of the weeds sir” - Tom Gerlach and Mr Coote",
  "“Tom, where’s your homework?” - Mr Coote",
  "“I lost it on my iPad” - Tom Gerlach",
  "*See following pages…”  in corner of work- Brad Anderson",
  "“The bell is a reminder for the teacher” - Mr Jessett",
  "“Roz is gun”- the year nine bibles",
  "*Miss Bonny starts new unit on drugs* “Will there be a prac assessment miss?” - Andre Rossitt",
  "“You belong in the special needs playgroup” - Mr Jessett",
  "“You know what we don’t need? We don’t need kids on meds.” - Alex Clements",
  "“Miss, are you American or Canadian?” - Sean Farraway",
  "“If you were born in Atlanta does that make you Atlantic?” - Peter Woodhead",
  "*Sean Farraway is being annoying* “Be quiet, annoying orange.” *Whole class goes nuts* - Mrs. Hughes"
];

module.exports = quotes.map((quote, idx) => ({ id: idx + 1, quote }));